name: semojo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter_signin_button: 2.0.0
  dropdown_search: 2.0.1
  http: 0.13.4
  reorderable_grid_view: 2.2.2
  flutter_staggered_grid_view: 0.6.0
  persistent_bottom_nav_bar: 4.0.2
  firebase_core: 1.11.0
  google_sign_in: 5.2.3
  firebase_auth: ^3.3.5
  get_storage: 2.0.3
  flutter_facebook_auth: 4.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

